package zhanghegang.com.bawei.onetime.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VER_SION_DOWN_TABLE".
*/
public class VerSionDownTableDao extends AbstractDao<VerSionDownTable, Long> {

    public static final String TABLENAME = "VER_SION_DOWN_TABLE";

    /**
     * Properties of entity VerSionDownTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ThreadId = new Property(1, String.class, "threadId", false, "threadId");
        public final static Property StartIndex = new Property(2, int.class, "startIndex", false, "startIndex");
        public final static Property EndIndex = new Property(3, int.class, "endIndex", false, "endIndex");
    }


    public VerSionDownTableDao(DaoConfig config) {
        super(config);
    }
    
    public VerSionDownTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VER_SION_DOWN_TABLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"threadId\" TEXT," + // 1: threadId
                "\"startIndex\" INTEGER NOT NULL ," + // 2: startIndex
                "\"endIndex\" INTEGER NOT NULL );"); // 3: endIndex
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VER_SION_DOWN_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VerSionDownTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String threadId = entity.getThreadId();
        if (threadId != null) {
            stmt.bindString(2, threadId);
        }
        stmt.bindLong(3, entity.getStartIndex());
        stmt.bindLong(4, entity.getEndIndex());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VerSionDownTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String threadId = entity.getThreadId();
        if (threadId != null) {
            stmt.bindString(2, threadId);
        }
        stmt.bindLong(3, entity.getStartIndex());
        stmt.bindLong(4, entity.getEndIndex());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public VerSionDownTable readEntity(Cursor cursor, int offset) {
        VerSionDownTable entity = new VerSionDownTable( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // threadId
            cursor.getInt(offset + 2), // startIndex
            cursor.getInt(offset + 3) // endIndex
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VerSionDownTable entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setThreadId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStartIndex(cursor.getInt(offset + 2));
        entity.setEndIndex(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(VerSionDownTable entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(VerSionDownTable entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(VerSionDownTable entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
